[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.19'
bytecode_hash = "none"
cbor_metadata = false
optimize = true
via-ir = false
runs = 1000000

fs_permissions = [{ access = "read-write", path = "./results"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
